from argparse import ArgumentParser
from os import sysconf
from pathlib import Path

from watchopticalreport2020.generatereport import generatereport
from watchopticalutils.log import getlog

_log = getlog("watchopticalreport2020")


def main():
    args = parsecml()
    if not args.input_directory.exists():
        _log.error(f"Input directory doe snot exists: {args.input}")
        sysconf.exit(1)
    _process(args.input_directory, args.output)
    return


def parsecml():
    parser = ArgumentParser()
    parser.add_argument(
        "input_directory",
        help="Location of plots generated by watchopticalanalysis package.",
        type=Path,
    )
    parser.add_argument(
        "--output", "-o", help="Output directory.", default=Path("./report"), type=Path
    )
    return parser.parse_args()


def _process(inputpath: Path, outputpath: Path):
    outputpath.mkdir(exist_ok=True, parents=True)
    report = generatereport(inputpath, outputpath)
    for fname in sorted(report.formats.values()):
        _log.info(f"Generated: {fname.absolute()}")


if __name__ == "__main__":
    main()
